name: Website Deploy

on:
    workflow_dispatch:
    schedule:
        - cron: '0 4 * * *'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: 迁出分支
              uses: actions/checkout@v3

            - name: 获取 pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 'latest'

            - name: 获取 NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: '22.13.0'
                  cache: 'pnpm'

            - name: 初始化
              run: pnpm install

            - name: 构建站点
              run: pnpm build-project

            - name: 部署到 Netlify
              uses: nwtgck/actions-netlify@v3.0
              with:
                  publish-dir: './build/dist'
                  deploy-message: 'Deploy from GitHub Actions'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
